### Задание 1

In [4]:
import numpy as np

In [5]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [6]:
for i in range(2, 13):
    if 12 % i == 0:
        b = int(12 / i)
        print(np.reshape(a, (i, b)))
        print('\n')

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]




### Задание 3

In [7]:
for i in range(2, 13):
    if 12 % i == 0:
        if i < 6:
            print(np.reshape(a, (-1, i)))
        else:
            print(np.reshape(a, (i, -1)))
        print('\n')

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]




### Задание 4

Нет

### Задание 5

In [44]:
a = np.random.normal(size = (3, 4))
a

array([[-0.42804606, -0.74240684, -0.7033438 , -2.13962066],
       [-0.62947496,  0.59772047,  2.55948803,  0.39423302],
       [ 0.12221917, -0.51543566, -0.60025385,  0.94743982]])

In [46]:
b = a.flatten()
a.size == b.size

True

### Задание 6

In [47]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [48]:
b = np.reshape(a, (1, 10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a - одномерный, b - двумерный

### Задание 8

In [49]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
c.size

10

### Задание 9

In [51]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
A = a.reshape((4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [54]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [55]:
B.shape

(4, 4)

In [56]:
det = np.linalg.det(B)
det

0.0

Вычислить обратную матрицу не получится, так как полученная матрица - вырожденная, ее определитель равен 0

### Задание 10

In [57]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [58]:
np.random.seed(3)

In [59]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

### Задание 11

In [60]:
c = np.random.randint(0, 16, 16)
c

array([12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5,  4])

### Задание 12

In [61]:
C = c.reshape(4, 4)
C

array([[12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7],
       [ 7,  2,  5,  4]])

In [62]:
D = B + C * 10
D

array([[125,  54,  83, 122],
       [ 34, 110, 186, 222],
       [ 93, 126, 179, 282],
       [102, 142, 262, 342]])

In [63]:
np.linalg.det(D)

-23916799.999999993

In [64]:
np.linalg.matrix_rank(D)

4

In [65]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01146976, -0.00043819, -0.00342855, -0.00098006],
       [ 0.01503211,  0.04559807,  0.0153666 , -0.04763179],
       [ 0.00637209,  0.01086767, -0.02412697,  0.01056663],
       [-0.01454375, -0.02712737,  0.0131255 ,  0.01489831]])

### Задание 13

In [66]:
D_inv[D_inv <= 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 1.]])

In [67]:
np.all((D_inv == 1) | (D_inv == 0))

True

In [69]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,   4,   6,   9],
       [ 14,  50,  86,  10],
       [ 23,  86,   3, 212],
       [  7,   2, 212, 302]])