### Задание 1

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [12]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [15]:
rows, columns = a.shape
result = a_centered_sp / (rows - 1)
result

2.0

### Задание 4

In [18]:
cov_2 = np.cov(a.T)
cov_2[0, 1]

2.0